name: beitak_app
description: بيتك - خدمات منزلية في الأردن
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  dotted_border: ^2.0.0+3
  file_picker: ^10.3.7
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.2
  go_router: ^15.1.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  phosphor_flutter: ^2.1.0
  pinput: ^5.0.2
  record: ^6.1.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  translator: ^1.0.4+1
  url_launcher: ^6.3.2

  # ✅ لازم للمايك (حفظ ملف مؤقت)
  path_provider: ^2.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
