name: beitak_app
description: بيتك - خدمات منزلية في الأردن
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.2
  get_it: ^9.0.5
  go_router: ^15.1.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  phosphor_flutter: ^2.1.0
  pinput: ^5.0.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
